### ISSUE TITLE
Support named arguments in parameter list

### ISSUE THREAD

**Issue by eproxus** [max-au/argparse#15]
Is there/will there be any support for named arguments in the parameter list _before_ the description? E.g `DEPTH` in the following example:

```
  -L, --level DEPTH          limit the depth of recursion
```

**Comment by max-au** [comment]
To understand a bit, do you have something like this:

    Cmd = #{arguments => [#{name => depth, long => "-level", short => $L, type => integer, help => "limit the depth of recursion"}]},
    argparse:help(Cmd)

And it currently prints this:

    usage: erl [-L <depth>] [--level <depth>]

    Optional arguments:
      -L, --level limit the depth of recursion

But you'd like to have a way to print this:

    usage: erl [-L <depth>]

    Optional arguments:
      -L, --level DEPTH limit the depth of recursion


Tthat seems to be a good feature request extending argument_help() semantic. Probably this way:

          help => {"[-L <depth>]", "limit the depth of recursion", "-L, --level DEPTH"}],

**Comment by max-au** [comment]
One more way to think about it:

```
-b, --initial-balance BAL      Initial balance value (float, 0.0)
                        ^ this here
```

**Comment by eproxus** [comment]
This is what I have right now:
```
        commands => #{
            "balance" => #{
                help => "show weekly hours balance",
                arguments => [
                    #{
                        name => initial_balance,
                        long => "-initial-balance",
                        short => $b,
                        help => "Initial balance value",
                        type => float,
                        default => 0.0
                    },
                    ...
                ]
            }
        }
```

The end result I'd want is this:

```
usage: erl [-b BAL ]
               ^ this here

Optional arguments:
  -b, --initial-balance BAL       Initial balance value (float, 0.0)
                        ^ and here
```

I don't think it makes sense to use different strings for the command summary and for the argument documentation.

Maybe `help` could be a map, like so:
```
help => #{text => "Initial balance value", arg => "BAL", type => "(a float)"}
```
where missing values are initialed to their defaults (e.g. `arg` to `"<initial_balance>"` and `type` to `"(float, 0.0)"`)? Not sure about the key name `arg` in there...

**Comment by max-au** [comment]
Starting with 1.1.4, there is a way to display usage this way:
```
Cmd = #{arguments => [#{name => balance, long => "-balance", short => $b, type => int, help => {"-b BAL", ["Initial balance value"]}}]}, 
argparse:help(Cmd).     

usage: erl -b BAL

Optional arguments:
  -b, --balance Initial balance value
```

I understand that it misses the second `BAL` in the optional argument list, but otherwise left column gets so wide that it leaves no space for the right column.
