### ISSUE TITLE
handling of default undefined or otherwise non-required args

### ISSUE THREAD

**Issue by zerth** [max-au/argparse#27]
I am finding it convenient to sometimes define `default => undefined` args to support handlers like this:

```
handler(#{foo := Foo, bar := Bar} = Args) -> ...
```

where `bar` was defined as `default => undefined`.  I.E., not require use of `maps:get(bar, Args, undefined)` or defaults merging for optional args.   This works, but then help text contains something like this unless overriding the long description:

```
Optional arguments:
  --bar some bar thing (undefined)
```

(the default value, `undefined`, is printed.  I think this would just confuse the user.)

I suppose I am asking if one of the following could be done:

1. Could non-required args be always passed in the args map with `undefined` values?  (Saw a comment describing the current behavior, but not why, and this seems conceptually similar enough if considering `undefined` as also meaning "absence of value".)
2. Or, could the default long help text perhaps omit `undefined` values?

**Comment by max-au** [comment]
For (2), you can define the argument this way:
```
    #{name => arg, default => undefined, help => {"-bar BAR", ["My own help message for bar"]}}
```
Help template is documented here: https://github.com/max-au/argparse/blob/master/doc/ARGPARSE.md#help-templates


The reason `undefined` is not considered to be "no value passed" is to be able passing `undefined` as a value. As you discovered, I did think of some magic value, although I thought of empty string (`""` or `[]`) to be that. Help line generated for empty string does look weird anyway:
```
Optional arguments:
  --bar some bar thing ()
```

So as soon as I faced the problem of picking the magic value, I got into analysis paralysis, and the only way out was not to introduce magic there. Hope the explanation helps.

**Comment by zerth** [comment]
I see, thanks.

For (1), I can't really think of a case where an app would need to distinguish "arg provided and interpreted as undefined" vs "arg not provided", but can accept that such cases could exist and that changing this behavior could open a modest can o' worms.

For (2), I did see that was possible but it's somewhat verbose when done for every such arg when the only intended difference from the `help => "X"` behavior is whether the default value/type is printed.

**Comment by max-au** [comment]
Posting here for posterity, the other suggestion by @zerth is to introduce a global switch to `argparse:parse/3` to control the behaviour. Sounds like an interesting idea.

**Comment by zerth** [comment]
> the other suggestion by @zerth is to introduce a global switch to argparse:parse/3 to control the behaviour

(Perhaps passed via options so as to work via `cli:run/2`, e.g., `cli:run(Args, #{missing_optional_args => undefined})`)

**Comment by max-au** [comment]
This you can have right now by using positional handlers, see https://github.com/max-au/argparse/blob/master/doc/CLI.md#handler-specification
(probably needs a highlight there)
```
    <...>
    handler => {fun start/2, undefined},
    arguments => [#{name => arg1}, #{name => arg2}] %% expect 2 arguments
    <...>


start(Arg1, Arg2) -> %% if Arg2 is not specified, you'll get `undefined`
  <...>

```

**Comment by zerth** [comment]
I see, although not quite the same especially when passing around a potentially large options map.
