### ISSUE TITLE
Feature Request: Add displayed default value

### ISSUE THREAD

**Issue by eproxus** [max-au/argparse#8]
Currently flags which have custom parsing generate "nonsense" help text. For example, the following argument:

```erlang
DefaultRange = {{2020, 1, 1}, {2020, 6, 22}},
#{
    arguments => [
        #{
            name => range,
            long => "-range",
            short => $r,
            help => "date range ([<from>]..[<to>])",
            type => {custom, fun(S) -> parse_range(S, DefaultRange) end},
            default => DefaultRange
        }
    ]
}
```

Generates the following text:

```
  -r, --range   date range ([<from>]..[<to>]), [{{2020,1,1},{2020,6,22}}]
```

However, if `parse_range(S, DefaultRange)` wants to e.g. take ISO dates there should be a way to display a default help string as well:

```
  -r, --range   date range ([<from>]..[<to>]), [2020-01-01..2020-06-22]
```

or when the default help string is set to `""` (or `undefined` or something similar):

```
  -r, --range   date range ([<from>]..[<to>])
```

**Comment by max-au** [comment]
This has been implemented in https://github.com/max-au/argparse/tree/help_template

**Comment by max-au** [comment]
This has also been implemented. It is now possible to use templates in the help message, this way:
https://github.com/max-au/argparse/blob/master/test/argparse_SUITE.erl#L668
